call ./config.bat
:: This script assumes that all SSH setup has already been done.
:: An SSH key can be generated by using `ssh-keygen` after installing Git [?]. Paste the contents of the file `<home>/.ssh/id_rsa.pub` into the designated GitHub/etc account settings.
mkdir public
cd ./public
git init
git remote add origin %ssh_url%
git pull origin master
cd ../